{% set version = '0.6-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tsmodel
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tsModel_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tsModel/tsModel_{{ version }}.tar.gz
  sha256: f8bbf75216fcf204d87873eab43f8a44ae27e140e5b83446d13ce867ed5f2ded

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('tsModel')"           # [not win]
    - "\"%R%\" -e \"library('tsModel')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tsModel
  license: GPL-2.0-or-later
  summary: Tools for specifying time series regression models.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: tsModel
# Title: Time Series Modeling for Air Pollution and Health
# Depends: R (>= 3.0.0)
# Imports: splines, stats
# Suggests: testthat
# Version: 0.6-2
# Author: Roger D. Peng <roger.peng@austin.utexas.edu>, with contributions from Aidan McDermott
# Maintainer: Roger D. Peng <roger.peng@austin.utexas.edu>
# Description: Tools for specifying time series regression models.
# License: GPL (>= 2)
# NeedsCompilation: no
# Packaged: 2024-06-25 14:08:56 UTC; rp34949
# Repository: CRAN
# Date/Publication: 2024-06-25 21:20:01 UTC
